# -*- coding: utf-8 -*-
"""Ass7-Decision_Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sUx4sZPhLau147Ba0293IKdsVRzghHpw
"""

import graphviz 
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import tree

PlayTennis=pd.read_csv('PlayTennis.csv')
print(PlayTennis)

Le = LabelEncoder()

PlayTennis['Outlook'] = Le.fit_transform(PlayTennis['Outlook'])
PlayTennis['Temperature'] = Le.fit_transform(PlayTennis['Temperature'])
PlayTennis['Humidity'] = Le.fit_transform(PlayTennis['Humidity'])
PlayTennis['Wind'] = Le.fit_transform(PlayTennis['Wind'])
PlayTennis['Play Tennis'] = Le.fit_transform(PlayTennis['Play Tennis'])
print(PlayTennis.head());

y = PlayTennis['Play Tennis']
X = PlayTennis.drop(['Play Tennis'],axis=1)

clf = tree.DecisionTreeClassifier(criterion = 'entropy')
clf = clf.fit(X, y)
tree.plot_tree(clf)


dot_data = tree.export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 
print(graph)

# The predictions are stored in X_pred
X_pred = clf.predict(X)
# verifying if the model has predicted it all right.
X_pred == y

print(X_pred);